---
- hosts: postgresql_db
  gather_facts: true
  become: false
  vars:
    root_base_dir: "~/app/"
    install_prereq: false
  roles:
    - name: postgresqldb
      base_dir: "{{root_base_dir}}"
      become: true
      become_user: postgres