---
- hosts: user_api
  gather_facts: true
  become: false
  vars:
    root_base_dir: "~/app/"
    install_prereq: false
  roles:
    - name: userapi
      base_dir: "{{root_base_dir}}"
      become: true