- name: Check if postgresqldb is already installed
  command: dpkg-query -l postgresql
  register: postgresqldb_check
  ignore_errors: true

- name: apt-get update
  command: apt update
  become: true

- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: Install postgresql db now.
  apt: name={{item}}
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
  become: true
  when: ((ansible_os_family == 'Debian')and((postgresqldb_check.stdout.find('no packages found') != -1)or(postgresqldb_check.stderr.find('no packages found') != -1)))


- name: Ensure postgresql db is started and enabled at boot.
  service:
    name: postgresql
    state: started
    enabled: yes