- name: Check if openjdk is already installed
  command: dpkg-query -l openjdk-8-jdk
  register: openjdk_check
  ignore_errors: true

- name: apt-get update
  command: apt update
  become: true

- name: Install openjdk now.
  package: name=openjdk-8-jdk state=present
  become: true
  when: ((ansible_os_family == 'Debian')and(openjdk_check.stdout.find('no packages found') != -1))

- name: Install openjdk now.
  package: name=openjdk-8-jre state=present
  become: true
  when: ((ansible_os_family == 'Debian')and(openjdk_check.stdout.find('no packages found') != -1))
