---
- name: update apt
  shell: apt update
  become: true

- name: install python apt
  shell: apt install -y {{item}}
  with_items:
    - build-essential
    - python-apt
    - python-pip
    - python-pexpect
    - awscli
  become: true

- include: install_tomcat.yaml
- include: install_nginx.yaml
- include: install_postgresql.yaml
